name: remote ssh command
on: 
  push:
    branches: [ main ]

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      uses: appleboy/ssh-action@master
      with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Ubah directory ke root project
      run: |
        cd /home/gulagulali/project/Laborat-Klinik-Web
        git pull
        sudo pm2 stop laravel-app
        php artisan migrate:fresh --seed
        sudo pm2 start laravel-app

 